version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./db:/db
    ports:
      - 5432:5432
  server:
    build: ./server
    env_file:
      - ./.env
    links:
      - "database:db"
    ports:
      - 3000:3000
  etl:
    build: ./etl
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - ./.env
    links:
      - "database:db"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
