version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - ./.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./db:/db
    ports:
      - 5432:5432
  etl:
    build: ./etl
    command: ["python3", '/app/src/covid-data.py']
    env_file:
      - ./.env
    volumes:
      - ./etl:/app
    links:
      - "database:db"
volumes:
  database-data: # named volumes can be managed easier using docker-compose
