version: 2
jobs:
  build-and-test-server:
    working_directory: ~/project/server
    docker:
      - image: circleci/rust
    environment:
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      # If you have committed your Cargo.lock file to version control
      # delete this step.
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test

  format-server:
    working_directory: ~/project/server
    docker:
      - image: circleci/rust
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install formatter
          command: rustup component add rustfmt
      - run:
          name: Formatting
          command: cargo fmt --all -- --check

  lint-server:
    working_directory: ~/project/server
    docker:
      - image: circleci/rust
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          name: Linting
          command: cargo clippy

  lint-client:
    docker:
      — image: circleci/node:7.10
    working_directory: ~/project/www
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Installing
          command: npm install
      — run:
          name: Linting
          command: npm run lint

  format-client:
    docker:
      — image: circleci/node:7.10
    working_directory: ~/project/www
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Installing
          command: npm install
      — run:
          name: Formatting
          command: npm run format
  deploy-client:
    docker:
      — image: circleci/node:7.10
    working_directory: ~/project/www
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Installing
          command: npm install
      — run:
          name: Building
          command: npm run build
      — run:
          name: Running deploy.sh
          command: ./deploy.sh


workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test-server:
          filters:
            tags:
              only: /.*/
      - format-server:
          filters:
            tags:
              only: /.*/
      - lint-server:
          filters:
            tags:
              only: /.*/
      - format-client:
          filters:
            tags:
              only: /.*/
      - lint-client:
          filters:
            tags:
              only: /.*/
      - deploy-client:
          requires:
            - format-client
            - lint-client
