version: 2
jobs:
  build-and-test-server:
    working_directory: ~/project/server
    docker:
      - image: circleci/rust
    environment:
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Switch to nightly
          command: rustup toolchain install nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      # If you have committed your Cargo.lock file to version control
      # delete this step.
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test

  deploy-server:
    working_directory: ~/project/server
    docker:
      - image: circleci/rust
    environment:
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker
      - run:
          name: Switch to nightly
          command: rustup toolchain install nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      # If you have committed your Cargo.lock file to version control
      # delete this step.
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --release
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
          key: v1-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Running deploy.sh
          command: sh ./deploy.sh

  check-server:
    working_directory: ~/project/server
    docker:
      - image: circleci/rust
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Switch to nightly
          command: rustup toolchain install nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install formatter
          command: rustup component add rustfmt
      - run:
          name: Formatting
          command: cargo fmt --all -- --check
      - run:
          name: Install Clippy
          command: rustup component add clippy
      - run:
          name: Linting
          command: cargo clippy

  build-client-image:
    working_directory: ~/project/www
    docker:
      - image: circleci/node
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker
      - run:
          name: Installing
          command: npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Formatting
          command: npm run format
      - run:
          name: Building
          command: npm run build
      - run:
          name: Running deploy.sh
          command: sh ./deploy.sh


  deploy-etl:
    working_directory: ~/project/etl
    docker:
      - image: circleci/python
    steps:
      - checkout:
          path: ~/project
      - setup_remote_docker
      - run:
          name: Running deploy.sh
          command: sh ./deploy.sh


workflows:
  version: 2
  build-test:
    jobs:
      - deploy-etl
      - build-and-test-server:
          filters:
            tags:
              only: /.*/
      - check-server:
          filters:
            tags:
              only: /.*/
      - deploy-server:
          requires:
            - build-and-test-server
            - check-server
      - build-client-image
